### ISSUE TITLE
Running a script

### ISSUE THREAD

**Issue by TwinMist** [ohnotnow/cronmon#20]
Hi how do you go about configuring a task to run a script?

thanks

**Comment by ohnotnow** [comment]
Hi,

I'm not sure what you mean?  Can you give me an example of what you're wanting to do?

**Comment by TwinMist** [comment]
Via the web gui can i configure a script to run. I do not see where to
configure the script
Thanks

**Comment by TwinMist** [comment]
Ie what to add all my lines in my cron file to your system

**Comment by ohnotnow** [comment]
Do you mean what command to run in your own cron job script?  If so, when you're viewing a job it should have an example of what to do for php, bash, powershell and python.  You pretty much just need to do an http get to http://your-cronmon/long-uuid-of-your-job.

**Comment by ufukart** [comment]
@TwinMist I understand you. This is not (unhappily) a web based cronjobs tool. I thought so too. This is only for monitoring cronjobs. For example, you running a cron in your script, adding http request a unique link from this tool. If your job not run and not request this link given period, system alerting you wtih a email.

@ohnotnow  Maybe you can do it. Like this https://codecanyon.net/item/web-cronjobs/15716288
A Web based cronjob tool. Only one cron to webbased cronjob tool and all other crons in this web based tool.

(I'm sorry my English is not good.)

**Comment by ohnotnow** [comment]
Hi,

I don't think I'll be adding the ability to _manage_ cronjobs.  That would be way out of scope for the tool.
